### ISSUE TITLE
vector feedback

### ISSUE THREAD

**Issue by clankill3r** [knupel/Rope#4]
continued from https://github.com/sampottinger/processing/issues/111

>  I know the convention about the uppercase for the classes name, and I do it to be similar of the GLSL convention and I I assume this weird choice but very logic for me, because I want considere the vec like a type, not like a class. I'm not real expert coder, more artist coder for me when you know the rules sometime it's can be necessary to break it. In this case I considere it's a time to break the rule.

Yeah I do the same thing some times, it's nice so you can copy functions between java and glsl.
If you do this I would suggest to never add static methods to the class.

> but is I understand when Java when variable is not instantiate that's not a problem for the memory ?

The variables are always default initialised.

you could do:

```java
class Vec2 {
   float x;
   float y;
}

class Vec3 extends Vec2 {
   float z;
}
```

Then for your `bvec`, I don't know what the reason is for this, but if it is memory. A boolean is not one byte (I used to think this). The size of a boolean is the same as a float (in x86). This is due that a pointer to a memory address is 32 bit in x86. It can not point to anything smaller. 

Personally I think you are falling into the trap of OOP. I felt in there myself, and only few climb out.

**Comment by StanLepunK** [comment]
Thanks for your feedback, but I think if I do that avec I cannot use the method `vec`without rewrite all those method in each class `vec2``vec3``vec4``vec5``vec6` I must balance the disadventage and the advantage of that. I don't have a feeling to 16 type in my class Vec make slowdown in the program... but maybe I'm wrong, now all compuer have a lot of memory ?
